# Generated by Django 3.1 on 2023-03-04 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_signup.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addhaardocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(null=True)),
                ('addharnumber', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=login_signup.models.path_and_rename_for_resume)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addhar_number', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
