import { Box, Button, Text, useToast } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  const toast = useToast();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Button
            onClick={(e) =>
              toast({ title: "Account created.", isClosable: true })
            }
          >
            hey
          </Button>
          <Text>hey</Text>
        </Box>
      </main>
    </>
  );
}
